# Generated by Django 3.2.4 on 2022-06-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20220618_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='../static/images/default.jpg', null=True, upload_to=''),
        ),
    ]
